apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001

