apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # You can specify a nodePort here or leave it out to have Kubernetes assign one.
  selector:
    app: todo-frontend

