apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app-chart.fullname" . }}-frontend
  labels:
    {{- include "todo-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ include "todo-app-chart.fullname" . }}-frontend
