apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app-chart.fullname" . }}-backend
  labels:
    {{- include "todo-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app-chart.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "todo-app-chart.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: MONGODB_URI
              value: "{{ .Values.backend.env.MONGODB_URI }}"  
